project:
  type: website

website:
  title: "Diego Hermoza"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/diegohc1
      - icon: twitter
        href: https://twitter.com/Dhermoza1
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

