project:
  type: website

website:
  title: "Diego Hermoza"
  site-url: https://dhermozac.netlify.app/
  description: "Probando un blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/diegohc1
      - icon: twitter
        href: https://twitter.com/Dhermoza1
      - icon: rss
        href: index.xml
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

